services:
  cow:
    build: .
    image: sga-office:latest
    env_file:
      - .env
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - "5101:5001"
    volumes:
      - ./instance:/app/instance
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first